# Site settings
name: DarkTime
email: gaojinchuande@163.com
author: chuange
#url: http://www.hifreud.com
#resume_site: http://www.hifreud.com/Resume.io/
#github: https://github.com/luoyan35714/
baseurl:
description: 如果这世界上真有奇迹，那只是努力的另一个名字
meta_description: 高金川;个人博客;平淡的生活，往往是最危险的
motto: 如果这世界上真有奇迹，那只是努力的另一个名字
banner: 平淡的生活，往往是最危险的

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: gaojinchuan
highlighter: Pygments

# Build settings
#markdown: kramdown
#kramdown:
#  input:  GFM
#  use_coderay: true
markdown: redcarpet
redcarpet:
    extensions: [ "fenced_code_blocks", "hard_wrap","autolink", "tables", "strikethrough", "superscript", "with_toc_data", "highlight", "prettify","no_intra_emphasis"]  
  

#FB:
  #comments :
    #provider : duoshuo
    #duoshuo:
        #short_name : luoyan35714
    #disqus :
        #short_name : freudkang
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light
